hashmapinc/Drillflow

- server/src/main/java/com/hashmapinc/tempus/witsml/server/WitsmlApiConfig.java
- server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java
- server/src/main/resources/application.properties
> this commit resolves #10 - version property

- src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java
- src/main/java/com/hashmapinc/tempus/witsml/server/api/model/cap/ServerCap.java
- src/main/resources/servercap.properties
this pull request is first version to fix #15
> 15-parameterization 

- pom.xml
- src/main/java/com/hashmapinc/tempus/witsml/server/WitsmlApiConfig.java
- src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java
- src/main/java/com/hashmapinc/tempus/witsml/server/api/model/cap/ServerCap.java
- src/main/resources/servercap.properties
> This PR resolves #15

- .gitignore
- Makefile
- additions to the root-level `.gitignore` file to remove vscode stuff, java-version stuff, and a few other `.*` files.
- addition of a basic root-level `Makefile` because I'm a caveman and don't use an IDE
P.S. - Feel free to reject this, I can just ignore the `Makefile` and resubmit a PR with just the `.gitignore`
> Basic dev environment changes made by Randy Pitcher

- .gitignore
- Makefile
- df-server/pom.xml
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/QueryContext.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/AbstractValve.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/mock/MockValve.java
- df-valve/test/java/com/hashmapinc/tempus/witsml/valve/ValveFactoryTest.java
- pom.xml
- all work done during the thanksgiving holiday week
See the branch for specific issue-based PRs
> Thanksgiving Dev

- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/ValveAuthenticationProvider.java
- df-server/src/main/resources/application.properties
- df-server/src/test/resources/application.properties
- df-server/src/test/resources/basemessages.properties
- df-server/src/test/resources/servercap.properties
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/ValveFactory.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java
This PR resolves #116. 
The properties are now places in an array in application.properties called **valveprop**. It is not the prettiest code ive written, but its the best i can do on friday afternoon.
> DF-116: Parameterization of the valve url and apikey

- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/IStore.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/model/WMLS_DeleteFromStoreResponse.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/model/WMLS_UpdateInStoreResponse.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/IValve.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/ValveException.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotValveTest.java
- df-valve/src/test/resources/log1311.xml
- df-valve/src/test/resources/log1411.xml
- df-valve/src/test/resources/trajectory1311.xml
- df-valve/src/test/resources/trajectory1411.xml
- df-valve/src/test/resources/well1311.xml
- df-valve/src/test/resources/well1311query.xml
- df-valve/src/test/resources/well1411.xml
- df-valve/src/test/resources/well1411query.xml
- df-valve/src/test/resources/wellbore1311.xml
- df-valve/src/test/resources/wellbore1411.xml
- `UpdateInStore` support in `IStore` / `StoreImpl`
- support for `updateObject` in `DotValve` for well objects
This connects to #125 
NOTE: I believe the code is correct for drillflow, but updates don't seem to take effect in Drilltest. I add a well, get the well, update with new info, then get again and don't see the updated change. Will need to work with Chris to find the bug in either Drillflow or Drilltest.
> df-125 -> DoT UPDATE for WELL

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java
- satisfyingly few code changes that lead to full WELLBORE UPDATE support in `DoTValve`!
This connects to #129
> df-129 -> DoT UPDATE for WELLBORE

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotTranslator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotValveTest.java
- DoT support for WELLBORE GET requests
- test suite for 1311/1411 WELLBORE getting
This connects to #128
> df-128 -> DoT GET for WELLBORE

- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/ValveAuthenticationProvider.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/IValve.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotAuth.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/ValveAuthException.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotValveTest.java
- Exception handling for Authenticate method.
- Validated the given credentials and throws the exception for incorrect credentials.
- test case to check for exception handling.
This connects to #115
> df-115->authenticate method for IValve should throw an exception

- df-server/src/main/resources/application.properties
- df-server/src/test/resources/application.properties
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotTranslator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/Util.java
Currently there is a shallow merge that occurs between the query and response. This PR resolves #150 by doing a deep merge recursively. PR #167 needs to be merged first as this is a carry forward.
> Performing a deep merge in the dot translator

- df-server/pom.xml
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/WitsmlApiConfig.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java
- df-server/src/main/resources/logback-spring.xml
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotAuthTest.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotValveTest.java
This PR resolves #173 and resolves #169.
it also resolves #178 because i went on a git rampage.
It directs the query depending on whether a UID is present in the add or not.
It also returns the UID for created objects (comma delimited for multiple adds at once).
> df-173: This PR resolves the no uid add vs uid add

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotAuth.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotTranslator.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotAuthTest.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotValveTest.java
- updates to the DoT test suites to point to the new, more secure QA server
- adding of `uidWell` query string to many `wellbore` rest requests
This connects to #184
> df-184 -> fix wellbore REST querying in DoT

- df-server/src/main/resources/application.properties
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotTranslator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/Util.java
- pom.xml
- upgrade to WitsmlObjects library v1.1.5
- fix to well DoT GetFromStore responses for fixing null/0/0.0/"" ambiguity and attribute expansion 
This connects to #202 
This connects to #170 
This connects to #196
> df-202 -> well WITSML response fix

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/ValveLogging.java
- logging object at com.hashmapinc.tempus.witsml.ValveLogging.
- It takes id, abstractWitsmlObject, message as parameters.
This connects to #191
> df-191->Create a Logging Object in df-valve

- pom.xml
- upgraded to witsml objects library v1.1.6 in project pom
This connects to #199
> df-199 -> fix bad wellbore json serialization

- df-server/src/main/java/com/hashmapinc/tempus/witsml/WitsmlUtil.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/WitsmlApiConfig.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/ValveAuthenticationProvider.java
- df-server/src/test/java/com/hashmapinc/tempus/witsml/server/api/StoreImplTests.java
- Fixed codacy issues with reference to : (https://app.codacy.com/app/Hashmap/Drillflow/issues/index)
This connects to #121
> df-121-> Fix All Codacy Issues

- df-server/src/main/resources/application.yml
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotClient.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/GraphQLQueryConverter.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/GraphQLRespConverter.java
This PR resolves #225 by adding graphQL support for wellbore.
> df-225 - Adding GraphQL support for wellbore

- .travis.yml
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/AppConstants.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/WitsmlServerApplication.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/IStore.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java
- df-server/src/test/java/com/hashmapinc/tempus/witsml/server/api/StoreImplTests.java
Implemented @EnabledAsync for Spring boot application with proxy target set to true and @Async for Store Impl methods with return type modified to CompletableFuture wrapped in entity objects
And provided a custom taskExecutor for thread pool configuration for async threads and return type of Store
This connects to #172
> df-172->Make spring async 

- pom.xml
- upgrade to witsml objects library v1.1.11 for artisan version conversion for wellbore objects.
This connects to #230
> df-230 -> integrated wellbore converter upgrades in WOL

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotTranslator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/GraphQLQueryConverter.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegatorTest.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotValveTest.java
- pom.xml
This pr resolves #253 by making the translator use the native converters.
> df-253: Updating drillflow to use the native converters

- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/AsyncAppConstants.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/WitsmlServerApplication.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java
- df-server/src/test/java/com/hashmapinc/tempus/witsml/server/api/AsyncTest.java
- df-server/src/test/java/com/hashmapinc/tempus/witsml/server/api/StoreImplTests.java
- df-valve/pom.xml
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/IValve.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotValveTest.java
- made spring async
- moved the async implementation to dotValve for CRUD operations
- implemented test case in df-server 
- tested with SOAP for add, update, delete and get
This connects to #172
> df-172-> make spring async

- df-valve/pom.xml
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/Util.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegatorTest.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/UtilTest.java
- pom.xml
- unit test for isEmpty method
- checked with null object 
- used powerMockito to test private method
This connects to #234
> df-234-> Unit test Dot util isEmpty method

- df-server/src/main/resources/application.yml
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotTranslator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java
This resolves #180. This supports Traj GET and then wires up the work done by randy which seems to work. There are a few bugs that will need to be ironed out but this gets the base implementation done.
> df:180: First pass at supporting full Traj CRUD, works for 1311 and 1411

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/GraphQLQueryConverter.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/GraphQLQueryConverterTest.java
- df-valve/src/test/resources/GraphQLResponse.json
- df-valve/src/test/resources/wellboreOpenQuery1411.xml
- pom.xml
Resolves #262.
There were three issues:
1) WOL was reporting dTim as dtim for ExtensionNameValue
2) JAXB was converting a null value to 0 for short, but magically it works for long, this was fixed in WOL for index of extension name value
3) The parentWellbore is actually referencing a 2.0 object so we could not query for the parent wellbore with the uid and name. The query had to convert value to title so the query would proceed.
> df-262 Fixing a complex wellbore query

- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegatorTest.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotTranslatorTest.java
This PR includes test cases for :
- consolidateObjectsToXML with well, wellbore and trajectory
- translateQueryResponse
This connects to #236
> df-236->Unit test DotTranslater

- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreValidator.java
This PR resolves #98 by creating a validation hook for all the main store methods.
> df-98: Commiting the validation hook for the WITSML error code returns

- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreValidator.java
- df-server/src/test/java/com/hashmapinc/tempus/witsml/server/api/StoreValidationTest.java
This resolves #279.
It adds the most common validation checks to add to store. This is the first step, will add the more esoteric ones later.
> Df-279: Adding the basic addToStore validation rules

- df-server/src/main/java/com/hashmapinc/tempus/witsml/WitsmlUtil.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreValidator.java
- df-server/src/test/java/com/hashmapinc/tempus/witsml/server/api/StoreImplTests.java
- df-server/src/test/java/com/hashmapinc/tempus/witsml/server/api/StoreValidationTest.java
This PR resolves #280.
The version string is now checked for and the default namespace is now checked for.
Additionally getcap is now validated and a bug was fixed in the way we parse options in.
> Df-280: This pr adds additional AddToStore validations and GetCap validations

- pom.xml
This PR resolves #288.
This issue was addressed in 1.1.24 of the WOL and this PR increases that version.
> df-288: Increasing the version of the WOL to avoid the trajectory issue

- pom.xml
- support for 1311 / 1411 log conversions with latest WOL changes
This connects to #232
> df-232 -> upgrade to new WOL that has log conversions

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotTranslator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegatorTest.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotTranslatorTest.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotValveTest.java
This PR resolves #204 by allowing a 1411 query to send in the returnElements=all option in. 
Additionally this PR resolves #303 by doing a null check on a check for size.
> df-204: This PR honors returnElements=all

- pom.xml
Upgrading to version of WOL that preserves uid and name after 2 to 14…11 conversion
this PR resolves #302
> df-302: Upgrading version of WOL to .26

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/JsonUtil.java
- pom.xml
This PR resolves #275 & resolves #311 and resolves #310 and resolves #309 .
It implements the patch functionality as well as upgrades the WOL to a version that handles custom data as well as trajectory UID handling.
> df-275: initial commit of the patch functionality

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/GraphQLQueryConstants.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/GraphQLQueryConverter.java
This PR resolves #297.
The recursive query generation was removed for Well and only remains for wellbore now.
> df-297: Converting the recursive logic to static logic for well query

- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/IStore.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java
This PR resolves #324 
StoreImpl was not returning suppMsgOut, now it is.
> df-324: Store Impl now returns suppMsgOut

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/GraphQLQueryConverter.java
This PR resolves #294
When a query is made with commonData/dTimLastChange then it is converted to lastUpdateTimeUTC.
> df-294: Adding lastUpdateTimeUTC to well graphqlquery

- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/ValveException.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java
Adding delete validation and enhancing valve exception to pass back defined error codes, this PR resolves #351. and adds validation to deletefromstore
> df-351: Adding delete validation 

- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/ValveAuthenticationProvider.java
- df-server/src/test/java/com/hashmapinc/tempus/witsml/server/api/StoreValidationTest.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/ValveFactory.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/client/DotClient.java
- pom.xml
This PR resolves #358. It creates a custom http client with a custom verifier to allow all certs. Super insecure but it was a request.
It also surfaces any error that is caused during the construction of the dot valve due to a problem creating the httpclient.
> df-358: Allowing self-signed certs in unirest

- df-server/src/main/resources/application.yml
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotTranslator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java
This PR resolves #365 
Added the code to address GetFromStore functionality.This is first commit for the GetFromStore.
> This PR resolves #365

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
This PR resolves #394 
Complete coding to address deleteFromStore
Added code in DotDelegator to address the changes.
> This PR resolves #394

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogConverterExtended.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegatorTest.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogConverterExtendedTest.java
Now should have channel set information in response.
> Df 364 Full Channel Set Response

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogConverterExtended.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotValveTest.java
This PR resolves #401
Fixed code for channels issue.
> This PR resolves #401

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/DotLogDataHelper.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogHelperTest.java
This PR resolves #426 by adding a converter method to the logDataHelper to convert to Witsml2.0 for the log data helper class.
> Df-426: This PR supports converting 1311 logData to WITSML 2.0 for Add and Update in store queries

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/ChannelSet.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/Index.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/ChannelSetConversionTest.java
Merged Update (working version)
> Merged at Last with Rest of Code Base!

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/ChannelSet.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/Index.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegatorTest.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/ChannelSetConversionTest.java
Commiting changes for UpdateInStore:Log. Merging earlier in the cycle avoids merge pain later. Fixed a v1.3.1.1 issue where the code was not mirroring v1.4.1.1 & results in a NullPointerException. Modified code so it is not as complex for version differences (allows side-by-side comparison). Documentation was incorrect. Other minor issues.
> df-395A Clean & Working version of UpdateInStore:Log

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/JsonUtil.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/DotLogDataHelper.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogConverterExtended.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/ClassIndexDeserializer.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogHelperTest.java
- [ x] Is there a Github ticket associated with this PR? Is it referenced 
- [x ] Does your PR title start with DF-XXXX where XXXX is the waffle number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x ] Has your PR been rebased against the latest commit within the target branch (typically master)?
- [ x] Have you ensured that the full suite of tests is executed via mvn clean install at the root Drillflow folder?
- [x ] Have you written or updated unit tests to verify your changes?
- [ x] Have you ensured that all Soap UI test cases pass
Please ensure that once the PR is …
> Df 452: This code adds filtering and respects requestedElements=all

- df-server/src/main/resources/application.yml
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
This PR resolves Df 447  to take care depth and time min/max index and min/mx DateTimeIndex
- [X ] Have you ensured …
> This PR resolves Df 447

- df-server/src/main/resources/application.yml
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/ChannelSet.java
To address this defect also do address df- 448 , df- 451, df - 449
- [ X] Have you ensured that all Soap UI test …
> This PR resolves #447

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
This to fix timedata getFromStore
- [X ] Have you added …
> This PR resolve Df 447

- df-server/src/main/resources/application.yml
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
This PR resolves #499
To Fix  Duplicate Env variable key
- …
> This PR resolves #499

- df-server/src/main/resources/application.yml
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/ChannelSet.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/Index.java
- docs/source/integration/dot/envvars.rst
Makes indexType match for DoT
- [ x] Is there a Github ticket associated with this PR? Is it referenced 
- [x ] Does your PR title start with DF-XXXX where XXXX is the waffle number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x ] Has your PR been rebased against the latest commit within the target branch (typically master)?
- [x ] Have you ensured that the full suite of tests is executed via mvn clean install at the root Drillflow folder?
- [x ] Have you written or updated unit tests to verify your changes?
- [ x] Have you updated Soap UI
- [x ] Have you ensured that all …
> df-510 indexType update from DoT

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogConverterExtended.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
This PR  for df-551 to address getFromStore with no logData
- …
> This PR  for df-551

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogConverterExtended.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/ChannelSet.java
This PR to resolve Df 551 for the scenario having logData in query.
- [ X] Have …
> This PR to resolve Df 551

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogConverterExtended.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/ChannelSet.java
This PR resolves commonData to be displayed in getFromStore
- [X ] Have you added documentation for any API related changes to the /docs folder
- [ X] Have you ensured that …
> This PR resolves Df 551

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/DotLogDataHelper.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogConverterExtended.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/ChannelSet.java
This PR resolves #568
GetFromStore Needs to Support Optional Data
- [ X] Have you ensured that all Soap UI test …
> This PR resolves #568

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
This PR resolves #448
This PR to address index and mnemonic filter
- [ X] Have you ensured that all Soap UI test …
> This PR resolves #448

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogConverterExtended.java
Added code logic to take care uidWell and uidWellBore for log …
> This PR resolves uidWell and uidWellBore for log

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
This PR to fix min and max dateTime
- [X ] Have you added …
> This PR to fix min and max dateTime

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogConverterExtended.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/Index.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegatorTest.java
This change resolves 454, 580, 566, and 505; there is 1 more minor change and 402 will close also.
- [ X] Have you …
> This PR to resolve DF 454, 580, 566, and 505

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegatorTest.java
DotDelgator was reaching an endpoint for channels "incorrectly"; Junit test proved this to be an issue, so it is now fixed. Also unused constants & documentation was "cleaned up".
- [X ] Have you ensured that the full suite of tests is executed via mvn clean install at the root …
> Closes df-402 AddToStore Junit & Updates DotDelgator

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogConverterExtended.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
This PR resolves min and max data calculations
- [X ] Have …
> This PR resolves min and max data calculations

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
This PR to Fix Addtostore and min max blank value check
- [ …
> This PR to Fix Addtostore and min max blank value check

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
This PR fix for validation min and max data
- [ X] Have you …
> This PR fix for validation min and max data

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogConverterExtended.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
This PR to fix for channels no logdata date format
- [X ] …
> This PR to fix for channels no logdata date format

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
This PR to fix code for time min max scenario
- [ X] Have …
> This PR to fix code for time min max scenario

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/DotLogDataHelper.java
This PR to fix for logdata index sorted order
- [ X] Have …
> This PR to fix for logdata index sorted order

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/DotLogDataHelper.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogConverterExtended.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogHelperTest.java
This PR to fix for logdata sort time scenario and RTC cases …
> This PR to fix for logdata sort time scenario and RTC cases

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/ChannelSet.java
- pom.xml
This PR  to Fix Datetime with string format for Log
- [ X] …
> This PR  to Fix Datetime with string format for Log

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
This PR to fix for Mnemonic only search
- [ X] Have you …
> This PR to fix for Mnemonic only search

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogConverterExtended.java
This PR resolves #622 and resolves #575 
> Adding logic fixes for 1.3.1.1

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogConverterExtended.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
- pom.xml
this resolves #637 by updating the WOL to fix the converter for channelindex and removing classindex
> Adding channel index and class index fixes

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/Index.java
- [ x] Is there a Github ticket associated with this PR? Is it referenced 
- [x ] Does your PR title start with DF-XXXX where XXXX is the waffle number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [ x] Has your PR been rebased against the latest commit within the target branch (typically master)?
- [ x] Have you ensured that the full suite of tests is executed via mvn clean install at the root Drillflow folder?
- [x ] Have you written or updated unit tests to verify your changes?
- [x ] Have you updated Soap UI
- [x ] Have you ensured that all Soap UI test cases pass
- [x …
> code fix for 1311 update

- df-server/src/main/java/com/hashmapinc/tempus/witsml/WitsmlObjectParser.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreValidator.java
- df-server/src/main/resources/application.yml
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotTranslator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java
- pom.xml
This PR for code change for fluids report
- [X ] Have you …
> This PR for code change for fluids report

- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
This PR code fix for delete operation
- [X ] Have you added …
> This PR code fix for delete operation

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotTranslator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java
- pom.xml
Fixes:
1. Rheometer data & uids
2 wellUid and wellBoreUid (let me know if we need names)
3. tempVis
4. md & tvd values are in the spot being tested
Still need:
1. to figure out why marshaling does not populate dTim OR hardnessCa
2. to figure out if md & tvd need to be placed into Fluid object
3. to figure out what to do for uom in asg
I think, however, this is a good candidate for a container.
> Release for Container 0.18.0

- df-server/src/main/resources/application.yml
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
> Fix For Changing ENV Variable Path

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/ChannelSet.java
- pom.xml
Code fix for DF - 644 object growing
- [X ] Have you ensured …
> DF - 644 object growing

- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/interceptors/PrettyLoggingFeature.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/interceptors/SensitiveEventSender.java
- df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/interceptors/SingleLineMessageFormatter.java
- df-utils/src/main/java/com/hashmapinc/tempus/witsml/ValveLogging.java
> df-392: Changing logging to be on one line

- README.md
> Correction to the sample docker run command in readme.md

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/DotLogDataHelper.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogConverterExtended.java
- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
- df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogHelperTest.java
> support to read channels and logData without index curves in 1411

- df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
> fix null reference exception in LOG GetFromStore if no min/max index
