hashmapinc/Drillflow

src/main/resources/basemessages.properties, src/main/resources/servercap.properties
This PR resolves #62 .
There were invalid characters in the properties files that generated un-parseable SOAP strings.
Additionally there was an erroneous property in servercap after a refactor.
=> 61-Fixing invalid characters in get base message

.gitignore, Makefile, README.md, docker/Makefile, src/main/java/com/hashmapinc/tempus/witsml/server/api/IStore.java, src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java, src/test/java/com/hashmapinc/tempus/witsml/server/api/WitsmlServerApplicationTests.java
- `.gitignore` DS_Store addition
- brand spankin' new `Makefile` for docker building
- WMLS_AddToStore implementation that just returns `1`
- simple test for WMLS_AddToStore implementation
This connects to #39
=> Drillflow 39 - WMLS_AddToStore endpoint skeleton

README.md, src/main/java/com/hashmapinc/tempus/witsml/server/api/IStore.java, src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java, src/main/java/com/hashmapinc/tempus/witsml/server/api/model/WMLS_GetCapResponse.java
This PR resolves #66 by addressing the invalid operation names. There are now legal operation names. The Readme has been updated, and an invalid WMLS_GetCapResponse name was addressed. SOAPUI can now import the Drillflow WSDL directly.
=> Drillflow-66 - invalid operation name

df-server/src/main/java/com/hashmapinc/tempus/witsml/valve/AbstractDelegator.java, df-server/src/main/java/com/hashmapinc/tempus/witsml/valve/AbstractTranslator.java
- implementation of the `AbstractTranslator` in `com.hashmapinc.tempus.witsml.valve` package
- implementation of the `AbstractDelegator` in `com.hashmapinc.tempus.witsml.valve` pacage
This connects to #50 
This connects to #51
=> df-50 and df-51 -> implement abstract valve translator / valve delegator

df-server/src/main/java/com/hashmapinc/tempus/witsml/WitsmlUtil.java, df-server/src/test/java/com/hashmapinc/tempus/witsml/WitsmlUtilTests.java
- addition of a static parser method in `WitsmlUtil` to convert valid `OptionsIn` witsml strings to `HashMap<String, String>` objects
- addition of testing suite for the `OptionsIn` parser utility method
This connects to #70
=> df-70 -> WitsmlUtil.parseOptionsIn utility method

df-server/pom.xml, pom.xml
Putting the spring deps back in df-server, and fixing the multi JSONObject warning. This resolves #117 and resolves #114.
Due to a simplification of the valve auth strategy, i was able to limit spring to just the df-server module, as the valve is injected via the authprovider and storeimpl only. The factory does the selection of the valve, and as such is not dependent on spring injection or awareness.
=> DF-117 and DF-114: Dependency Restructuring

df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java, df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/model/cap/ServerCap.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/IValve.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java
- addition of `getCap` to `IValve` to get capabilities directly from a valve
- implementation of `getCap` in `DotValve`
- logic in autowired `valve` constructor in `StoreImpl` that pulls valve-specific functionality directly from the `valve` in to the `cap` field.
This connects to #131
=> df-131 -> added Valve support for getCap

df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/IStore.java, df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java, df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/model/WMLS_DeleteFromStoreResponse.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/IValve.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/ValveException.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotValveTest.java, df-valve/src/test/resources/log1311.xml, df-valve/src/test/resources/log1411.xml, df-valve/src/test/resources/trajectory1311.xml, df-valve/src/test/resources/trajectory1411.xml, df-valve/src/test/resources/well1311.xml, df-valve/src/test/resources/well1311query.xml, df-valve/src/test/resources/well1411.xml, df-valve/src/test/resources/well1411query.xml, df-valve/src/test/resources/wellbore1311.xml, df-valve/src/test/resources/wellbore1411.xml
- support for WELL DELETE 
- upgraded DoTValve unit test suite to handle server errors gracefully
- expanded use of `ValveException` in `DotValve` for passing descriptive failure information to SOAP clients
- improved test input XML files
This connects to #126
=> df-126 -> DELETE support for DoTValve WELL

.travis.yml, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/IValve.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotValveTest.java
- refactoring of the `DoTValve.createObject` method to be more concise and to support an arbitrary number of `AbstractWitsmlObject`s
- added support for `wellbore` in `DoTValve` delete
- added test suite for 1311 and 1411 `wellbore` deletion
This connects to #130
=> df-130 -> support DELETE for WELLBORES in DoTValve

df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/IStore.java, df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java, df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/model/WMLS_AddToStoreResponse.java, df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/model/WMLS_GetBaseMsgResponse.java, df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/model/WMLS_UpdateInStoreResponse.java, df-server/src/main/resources/logback-spring.xml, df-server/src/test/java/com/hashmapinc/tempus/witsml/server/api/StoreImplTests.java
This PR resolves #155. 
It adds the response object for get base message, and adds the annotations for the response object types in Update and Add response objects (not super necessary right now, but will avoid some black magic breaking in the near future).
=> Fixing the response objects to more accurately reflect the WMLS wsdl

df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/IStore.java
This PR resolves #157. There was an erroneous header attribute added to the getcap response that forced the query response to be returned in the header vs the body.
=> Fixing an invalid header-response for getcap

df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotAuth.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotTranslator.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java
- support for forced token refreshing in DoTAuth
- automatic token refresh and retrying in ALL methods (they catch the bad token 301 from the auth server and retry 1 more time. I can extend this with cooldowns in the future)
- made the DotTranslator an all-static method holder
- moved DotValve getObject logic mostly into the delegator (thanks to the now-static DotTranslator)
This connects to #160
=> df-160 -> force refresh JWT's in DoTValve

df-server/src/main/resources/application.properties, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotAuth.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
This PR resolves #164 by adding Bearer to the Authentication header and removing the OCP key from all except the token broker
It also resolves #165 by updating all the paths for the well api
It finally resolves #166 by changing the key of the content type from accept to Content-Type
=> df-164: Integration testing fixes

df-server/src/main/java/com/hashmapinc/tempus/witsml/server/api/StoreImpl.java, df-server/src/main/resources/logback-spring.xml, df-valve/src/main/java/com/hashmapinc/tempus/witsml/QueryContext.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotValveTest.java
This PR resolves #192 
Currently the exchange id generated by CXF is useful for determining a total round trip time, however, not for understanding the intermediate query performance. Therefore the exchange id has been added to ensure that the query can be tracked from start to finish.
=> df-192: adding the exchange id to the query context

df-server/src/main/resources/application.yml, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotClient.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotClientTest.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotValveTest.java
This PR resolves #183 by parameterizing all rest paths in the valve configuration in the .yml file. It basically changes the constructor of the DotDelegator to take in the config map rather than just the key and the path...this way we can dynamically add more paths as more objects are supported.
The tests were updated to add the new config parameters for the paths.
The endpoints are as follows:
token.path
well.path
wellbore.path
=> DF-183: All endpoints now parameterized

df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegatorTest.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotValveTest.java
- support for trajectory add to store behavior
- creation of `DotDelegator` test suite with unit testing just for trajectory behavior (other tests are covered by another card)
This connects to #179 
NOTES:
- integration testing is necessary when trajectory support is fully deployed for DoT
- a witsml objects library hotfix was necessary to make 1411 trajectory objects properly return their version. If you're getting errors with this, please refresh your cash or upgrade your witsml objects library version.
=> df-179 -> support for create trajectory

df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotTranslator.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/Util.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotValveTest.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/UtilTest.java, df-valve/src/test/resources/utilTest/well1311dest.json, df-valve/src/test/resources/utilTest/well1311merged.json, df-valve/src/test/resources/utilTest/well1311src.json
- support for returning empty plural objects to clients when valid REST queries to DoT return 404 responses
- deep merging of nested complex JSONArray components in our util src/dest merging logic. A JSONArray used to be merged in if it was not "empty" (meaning []), but now "empty" is recursively inspected to ensure any array is considered empty if all of its sub elements are empty.
- testing to validate empty responses generate proper plural WITSML responses
- Util test suite and test json files to validate proper merging behavior for wells with nested JSONArray objects in the src object.
This connects to #218
=> df-218 -> fix bad well merging, support drillflow responses for non-error 404 DoT statuses

df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java
This resolves #245. 
RTC creates a wellbore without a UID, and it was causing the wellbore to be created, but the call would fail after succeeding in DoT because of how we check for UID's on the return.
There is now a null check before isEmpty, and this fixes the problem and RTC can create wellbores.
=> df-245: RTC can now create wellbores

df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotTranslator.java, pom.xml
There was an issue where common data was not being returned, and Jackson was setting dTimLastChanged to dtimLastChanged and thus not ser/dser correctly. I have added the common data strings to always be returned in dotTranslator, and increased the version of the WOL for the serialization fix.
=> df-239: Common data is now returned

df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotTranslator.java, pom.xml
This PR resolves #263.
The Trajectory crud translator now uses the native converter to down-convert the 1411 response to 1311 when the query is performed in 1311.
=> df-263: Converting to native trajectory converter

df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/Util.java
This resolves #269 
Fixing an invalid check in the merge logic that resulted in arrays of complex objects not being merged.
=> df-269: fixing an issue where all of the elements of the trajectory object are not returned

df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotTranslator.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/JsonUtil.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/Util.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegatorTest.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/JsonUtilTest.java, df-valve/src/test/resources/updateTest/WellCountryUpdate1311.xml, df-valve/src/test/resources/updateTest/WellCountryUpdateResult1311.json
This PR resolves #273
There was an issue when serializing an update query, that empty arrays would erroneously be sent and thus clearing DoT of any values in the complex object array. There is now a removeEmpties function in the JsonUtil class that will leverage the isEmpty method to remove those empty elements.
The Util Class has also been renamed to JsonUtil.
=> Df-273: Fixing update query creation by removing empty fields

df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/JsonUtil.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegatorTest.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotValveTest.java, pom.xml
This PR detects a DeleteFromStore request that is actually an element delete (meaning only deleting one tag of the xml document vs an entire object). It does this by executing a regex on the incoming XML. It was decided to read the query in vs serializing the AWO to avoid a separate and unnecessary serialization operation. The Regex will handle the following cases:
```xml
<object uid="x"></object> 
```
```xml
<object uid="x">
</object>
```
```xml
<object uid="x" />
```
```xml
<object uid="x"/>
```
Currently this PR only detects the element deletion by the regex failing to find a match of any of the cases above and then routing that to _performElementDelete_ in _DotDelegator_. This function only throws a ValveException to say element delete is not supported. This is intended to avoid the …
=> df-275: Creating the routing for element delete vs object delete

df-server/pom.xml
This card resolves #100 by upgrading CXF which now leverages the module system of java 10+ and does not throw the scary warning about blocking reflection.
=> df-100: Upgrading the version of cxf

df-server/src/main/java/com/hashmapinc/tempus/witsml/server/WitsmlApiConfig.java, df-server/src/main/resources/interceptor/removeReturn.xsl
This resolves #289 
The certification test tool was returning a <return> element that was preventing it from running. It is implemented as an XSLTOutInterceptor as this was the mechanism that is least error prone and the least amount of code. 
After quite a lot of testing it was found that string manipulation was error prone, and the XSLT is not complex, as the return messages are never structurally that big (largest being 4 return elements). The largest part is a simple text() element that is copied over thus reducing overhead.
=> df-289: Removing the <return> element from the response

df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/JsonUtil.java
This PR resolves #296 
This removes the empty arrays that are not legal on a query.
=> df-296: Fixing the merge logic

df-server/src/main/resources/application.yml, df-server/src/main/resources/logback-spring.xml, docs/source/integration/index.rst, docs/source/integration/logging.rst
This PR resolves #305.
This PR removes the colorized log output as requested, for ease of logging. The rolling file appender is still there however, not sure why that is not used.
This connects #327 for the documentation portion
=> df-305: Removing the colorized log output

df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/GraphQLQueryConstants.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/GraphQLQueryConverter.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/GraphQLQueryConverterTest.java
This PR resolves #329 and resolves #267.
1. Added provided WELLBORE_QUERY to com.hashmapinc.tempus.witsml.valve.dot.GraphQLQueryConstants.
2. Modified com.hashmapinc.tempus.witsml.valve.dot.GraphQLQueryConverter::createWellboreQuery to use the same technique as com.hashmapinc.tempus.witsml.valve.dot.GraphQLQueryConverter::getWellQuery in order to provide static "get everything logic"
3. Additionally, modified the switch statement in com.hashmapinc.tempus.witsml.valve.dot.GraphQLQueryConverter::getQuery to return what was provided in #2 above and remove an unreachable "return this.builder.GetGraphQLQuery();" statement.
4. Confirmed visually that the returned JSON was as expected (per the card, only with provided variables) AND confirmed that the SoapUI tests executed successfully.
5. Will …
=> Df-298: Building a static graphql query.

df-server/src/test/java/com/hashmapinc/tempus/witsml/server/api/AsyncTest.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/client/DotClient.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/client/DotRestCommand.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/client/UidUuidCache.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/graphql/GraphQLQueryConstants.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/graphql/GraphQLQueryConverter.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/graphql/GraphQLRespConverter.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegatorTest.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/DotValveTest.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/client/UidUuidCacheTest.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/graphql/GraphQLQueryConverterTest.java
- organization of the dot package into 2 new subpackages
- addition of the UidUuidCache class for uid/uuid mapping with a local concurrent hashmap inside the DF container.
- test cases for the cache
- general syntax / format tidying, particularly on variable/function naming.
This connects to #337
=> df-337 -> add uuid/uid caching support

df-server/src/test/java/com/hashmapinc/tempus/witsml/server/api/AsyncTest.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/GraphQLQueryConverterTest.java
This PR resolves #339.
1. Create an object from the test utility's "wellboreOpenQuery" resource that is comparable to the one created by the code-under-test. As with the tested code, dynamically check how to build the correct query fields within this object.
2. Get the code-under-test's open query object, and compare it to the one just created using the test utility's resource. Perform a deep comparison of the JSON values.
=> Df-339: Modify JUnit test for Df-298 Building a static graphql query

df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/client/DotClient.java
This PR resolves #338 .
Made the change for DotClient token cache From Hashmap  to ConcurrentHashmap.
We had the varriable HashMap<String, DecodedJWT> cache; and changed to ConcurrentHashMap<String, DecodedJWT> cache;
=> #338 Convert the DotClient token cache to ConcurrentHashmap

df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/AxisDefinition.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/DensData.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/MnemAlias.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/SensorOffset.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/WellDatum.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/AcquisitionTimeZone.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/ChannelSet.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/Citation.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/CommonData.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/DefaultDatum.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/ExtensionNameValue.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/Index.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/LogParam.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/Md.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/StepIncrement.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channelset/Value.java, df-valve/src/test/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/ChannelSetConversionTest.java, df-valve/src/test/resources/dotConversion/log1411.xml
This PR resolves #423 by adding the equivalence overrides for the channel and channel set objects.
=> df-423: adding equivalence checks for channel and channelset

df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogConverterExtended.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
This PR to fix df-551 - 
The start and end index is missing as they don’t store the index as a separate channel. The start and end of the depth index would have to equal the start and end index of the channelset…obviously this is only for the case where the logData is not requested. In that case, the start/end would reflect what is in the return.
- [ X] Have you ensured that the full suite of tests is …
=> This PR to Fix df-551

df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/LogConverterExtended.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
This PR to fix min and max data coming from DOT.
- [X ] …
=> This PR to fix min and max data coming from DOT

df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/model/log/channel/Channel.java
This PR to fix for channel set date format
- [X ] Have you …
=> This PR to fix for channel set date format

df-server/src/main/resources/application.yml, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotValve.java, df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/client/DotClient.java, docs/source/integration/dot/envvars.rst
This PR resolves #682 
Currently the solution requires the API key to be present to convert the Basic authentication to a JWT token provided by prism. This is not required anymore, and as such should be removed from the Drillflow DOT valve.
This PR removes it by taking the following steps:
1) Removing it from the DoTClient (as a function of the token refresh function)
2) Changing the DotClient instantiation by removing the need for the api key
3) Removing the api key from the application.yml
4) Removing the api key from the documentation
This was tested against the DrillOps town DemoCore API on Aug 22 and found to be working.
in the …
=> df-682: removing the api key requirement
